/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*Variables*/

/*SEMANA 00*/

/*Ejercicio-0.1*/

uint8_t my_variable = 0;

/*Ejercicio-0.2*/

uint8_t dec = 0;
uint8_t hex = 0;
uint8_t bin = 0;

/*Ejercicio 0.3*/

uint8_t a = 0;
uint16_t b = 0;
uint32_t c = 0;
uint8_t d = 0;

uint8_t e = 257;

/*Ejercicio 0.4*/

uint8_t a1 = 0;
int8_t b1 = 0;
int8_t c1 = 0;

/*Ejercicio 0.5*/

int8_t x = 0;
uint8_t y = 0;

/*Ejercicio 0.6*/

result = 0;

/*Ejercicio 0.7*/

uint8_t x1 = 0;

/*Ejercicio 0.8*/

uint8_t a2 = 0;
uint8_t b2 = 0;
uint8_t c2 = 0;

uint8_t r1 = 0;
uint8_t r2 = 0;
uint8_t r3 = 0;
uint8_t r4 = 0;

/*SEMANA 01*/

/*Ejercicio 1.1*/

uint8_t a3 = 0;
uint8_t b3 = 0;
uint8_t div_result = 0;
uint8_t mod_result = 0;
uint8_t mul_result = 0;

/*Ejercicio 1.2*/

uint8_t x2 = 0;
uint8_t y2 = 0;
uint8_t sum = 0;

/*Ejercicio 1.3*/

uint8_t val = 3;

/*Ejercicio 1.4*/

uint8_t z1 = 5;
uint8_t z2 = 0;
uint8_t z3 = 5;

uint8_t result1 = 0;
uint8_t result2 = 0;
uint8_t result3 = 0;

/*Ejercicio 1.5*/

/*Ejercicio 1.6*/



int main(void)
{

///*SEMANA 00*/
//
//	/*Ejercicio-0.1*/
//
//	uint8_t my_variable = 42;
//
//	/*Ejercicio-0.2*/
//
//	uint8_t dec = 65;
//	uint8_t hex = 0x41;
//	uint8_t bin = 0b01000001;
//
//	/*Ejercicio 0.3*/
//
//	uint8_t a = 255; /* prediccion: 11111111 */
//	uint16_t b = 255; /* prediccion: 11111111 */
//	uint32_t c = 255; /* prediccion: 11111111 */
//	uint8_t d = 256; /* prediccion: 00000000 */
//
//	uint8_t e = 257; /* prediccion: 00000001 */
//
//	/*Ejercicio 0.4*/
//
//	uint8_t a1 = 200; /* prediccion: 11001000*/
//	int8_t b1 = 200; /* prediccion: 11001000*/
//	int8_t c1 = -1; /* prediccion: 11111111*/
//
//	/*Ejercicio 0.5*/
//
//	int8_t x = 127; /* prediccion: -128*/
//	x = x + 1;
//
//	uint8_t y = 255; /* prediccion: 0*/
//		y = y + 1;
//
//		/*Ejercicio 0.6*/
//
//		result = 0x0F + 0x01; /* prediccion: 16*/
//		result = 0xFF + 0x01; /* prediccion: 256*/
//		result = 0xA0 + 0x5F; /* prediccion: 255*/
//		result = 0xA0 + 0x60; /* prediccion: 256*/
//
//		/*Ejercicio 0.7*/
//
//		x1 = 0x01; /* prediccion: 1*/
//		x1 = 0x02; /* prediccion: 2*/
//		x1 = 0x04; /* prediccion: 4*/
//		x1 = 0x08; /* prediccion: 8*/
//		x1 = 0x10; /* prediccion: 16*/
//		x1 = 0x20; /* prediccion: 32*/
//		x1 = 0x40; /* prediccion: 64*/
//		x1 = 0x80; /* prediccion: 128*/
//
//		/*Ejercicio 0.8*/
//
//		uint8_t a2 = 5;
//		uint8_t b2 = 0;
//		uint8_t c2 = 255;
//
//		uint8_t r1 = !a2; /* prediccion: 0*/
//		uint8_t r2 = !b2; /* prediccion: 1*/
//		uint8_t r3 = !c2; /* prediccion: 0*/
//		uint8_t r4 = ~c2; /* prediccion: 0, ya que es el complemento de c2 */
//
//		uint8_t r5 = ~a2; /* prediccion: 250, ya que es el complemento de a2*/
//
///*SEMANA 01*/
//
//		/*Ejercicio 1.1*/
//
//		uint8_t a3 = 17;
//		uint8_t b3 = 5;
//		uint8_t div_result = a3 / b3;  /* prediccion: 3, ya que es division entera*/
//		uint8_t mod_result = a3 % b3;  /* prediccion: 2, ya que es el sobrante de la diviscion entera*/
//		uint8_t mul_result = a3 * b3;  /* prediccion: 85, multiplicacion de las dos variables*/
//
//		/*Ejercicio 1.2*/
//
//		uint8_t x2 = 200;
//		uint8_t y2 = 100;
//		uint8_t sum = x2 + y2; /* prediccion: 44, ya que el contenedor de 8 bites es de 0-255, por lo que 300 - 256 es igual a 44*/
//
//		/*Ejercicio 1.3*/
//
//		uint8_t left1 = val << 1;
//		uint8_t left2 = val << 2;
//		uint8_t left3 = val << 3;
//		uint8_t right1 = val >> 1;
//
//		/*Ejercicio 1.4*/
//
//		uint8_t z1 = 5;
//		uint8_t z2 = 0;
//		uint8_t z3 = 5;
//
//		uint8_t result1 = 0;
//		uint8_t result2 = 0;
//		uint8_t result3 = 0;
//
//		if (z1)
//		{
//			result1 = 1;
//		}
//		else
//		{
//			result1 = 0;
//		}
//
//		if (z2)
//		{
//			result2 = 1;
//		}
//		else
//		{
//			result2 = 0;
//		}
//
//		if (z1 == z3)
//		{
//			result3 = 1;
//		}
//		else
//		{
//			result3 = 0;
//		}
//
//		/*Ejercicio 1.5*/
//
//		uint8_t counter = 0;
//
//		for(counter = 0; counter < 10; counter += 1)
//		{
//		volatile uint8_t paso = counter;
//		}
//
//		for(counter = 0; counter < 10; counter += 2)
//		{
//		volatile uint8_t paso = counter;
//		}
//
//		for(counter = 10; counter > 0; counter --)
//		{
//		volatile uint8_t paso = counter;
//		}
//
//		for(counter = 10; counter < 5; counter += 1)
//		{
//
//		}

		/*Ejercicio 1.6*/

	    uint8_t suma = 0;
	    uint8_t counter = 1;
	    uint16_t suma1 = 0;
	    uint8_t counter1 = 1;


		while(counter <= 10)
		{
			suma = suma + counter;
			counter++;
		}


		while(counter1 <= 100)
		{
			suma1 = suma1 + counter1;
			counter1++;
		}



    /* Loop forever */
	while(1){}
}
